# Site
# Site
name: "Ben's musings on life"
title: "Ben's musings on life"
description: "What ideas can bring us closer together?"
logo: 'assets/images/ben_shiny.jpg'
favicon: 'assets/images/ben_shiny.jpg'
baseurl: .
url: www.benburke.org
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Ben:
    name: Ben
    display_name: Ben
    gravatar: df9ebde38a071277852a98182e207110
    email: bernard.francis.burke@gmail.com
    web: https://www.benburke.org
    twitter: https://twitter.com/burkawitcz
    description: "Old School computer nerd"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
